version: '1.0.{build}'
configuration:
- Debug
platform: Any CPU
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
- appveyor-retry dotnet restore "gpp.sln" -v Minimal
build_script:
- dotnet build "gpp.sln" -c %CONFIGURATION% --version-suffix %LABEL%
#after_build:
#- dotnet publish "src\Web\WebUI\GlobalPollenProject.Web" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts\GlobalPollenProject.Web
test_script:
- dotnet test "gpp.sln" -c %CONFIGURATION%
- dotnet test "test\GlobalPollenProject.Persistence.Tests\GlobalPollenProject.Persistence.Tests.fsproj" -c %CONFIGURATION%
artifacts:
- path: artifacts\**\*.*
cache:
- '%USERPROFILE%\.nuget\packages'
