version: '3.4'

services:

  core.api:
    ports: 
    - "5201:80"
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=http://0.0.0.0:80

  webapigw:
    ports:
    - "5202:80"

  identity.api:
    ports:
    - "5203:80"

  web.ui:
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
    - "5100:80"
