version: '3.4'

# Uses let's encrypt SSL with a reverse proxy to expose web
# apps on a single host. Uses subdomains for different
# user-facing services.

services:

  web.ui:
    environment:
      - VIRTUAL_HOST=${GPP_EXTERNAL_DNS_NAME_OR_IP}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${GPP_EXTERNAL_DNS_NAME_OR_IP}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - ASPNETCORE_ENVIRONMENT=${DOTNET_ENV}
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - IdentityUrl= http://${GPP_EXTERNAL_DNS_NAME_OR_IP}:80
      - CallBackUrl=http://${GPP_EXTERNAL_DNS_NAME_OR_IP}:80

  web.api:
    environment:
      - VIRTUAL_HOST=api.${GPP_EXTERNAL_DNS_NAME_OR_IP}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${GPP_EXTERNAL_DNS_NAME_OR_IP}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - ASPNETCORE_ENVIRONMENT=${DOTNET_ENV}
      - ASPNETCORE_URLS=http://0.0.0.0:80

  identity.api:
    environment:
      - VIRTUAL_HOST=identity.${GPP_EXTERNAL_DNS_NAME_OR_IP}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${GPP_EXTERNAL_DNS_NAME_OR_IP}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - ConnectionStrings__UserConnection=Server=${USER_SQL_HOST},1433;Database=${USER_SQL_DB};User=${USER_SQL_USER};Password=${USER_SQL_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=${DOTNET_ENV}
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - WebsiteUrl=http://${GPP_EXTERNAL_DNS_NAME_OR_IP}:80

  webapigw:
    ports:
      - "5202:80"

  core.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=${DOTNET_ENV}

  core.eventstore:
    environment:
      - VIRTUAL_HOST=eventstore.${GPP_EXTERNAL_DNS_NAME_OR_IP}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=globalpollenproject.org
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - EVENTSTORE_DEV=false

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    depends_on:
      - identity.api
      - web.api
      - web.ui
      - core.eventstore
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - vhost:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
  
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.13
    container_name: nginx-proxy-le
    depends_on:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
  
volumes:
  certs:
  html:
  vhost:
  dhparam: