version: "3"
services:
  # webui:
  #   ports:
  #     - "80:80"
  #   build: .
  #   links:
  #     - redis
  #     # - userdb
  #     - eventstore
  # userdb:
  #   container_name: gpp-userdb
  #   image: microsoft/mssql-server-linux
  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
  eventstore:
    image: eventstore/eventstore:latest
    ports:
      - "2113:2113"
      - "1113:1113"