name: Push to master

on:
  push:
    branches: [ master ] 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Setup .NET 
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.100'
    - name: Set Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
    - name: Restore .NET tools
      run: dotnet tool restore
    - name: Restore dependencies
      run: dotnet restore gpp.sln
    - name: Build
      run: dotnet build gpp.sln
    - name: Run tests
      run: dotnet test gpp.sln
    - name: Build docker images
      run: docker compose -f docker-compose.yml build