name: Push to master

on:
  push:
    branches: [ master ] 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Setup .NET 
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Restore dependencies
      run: dotnet restore gpp.sln
    - name: Build
      run: dotnet build gpp.sln
    - name: Build
      run: dotnet test gpp.sln